#!/usr/bin/env python3
"""Descriptive statistics of the shipped dataset -> data/analysis/stats.json and docs/12_statistics.md.

Everything is computed from data/analysis/*.parquet (RAW_CONFIG decode, all occupied slots with age >= 1).
Camera-based error numbers are RAW differences to the camera box-growth reference and include camera noise.
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parents[1]
DATA = REPO / "data" / "analysis"
DOC = REPO / "docs" / "12_statistics.md"
NAMES = {"A": "A (development, mixed)", "B": "B (held-out, city)", "C": "C (held-out, highway)"}


def r(x, n=2):
    return None if x is None or (isinstance(x, float) and not np.isfinite(x)) else round(float(x), n)


def drive_stats(S: pd.DataFrame, C: pd.DataFrame) -> dict:
    rec = S.groupby(["seg", "t"])
    per_rec = rec.size()
    minutes = S.groupby("seg").t.agg(lambda t: t.max() - t.min()).sum() / 60
    T = S.groupby(["seg", "track"]).agg(t0=("t", "min"), t1=("t", "max"), amax=("age", "max"), slot=("slot", "first")).reset_index()
    T["life"] = T.t1 - T.t0
    st = S[S.age >= 60]
    ego = rec.v_ego.median()
    vg = st.v_ground
    out = {
        "segments": int(S.seg.nunique()),
        "minutes_decoded": r(minutes, 1),
        "records": int(len(per_rec)),
        "records_per_s": r(len(per_rec) / (minutes * 60), 2),
        "object_samples": int(len(S)),
        "objects_per_record": {"mean": r(per_rec.mean()), "p95": r(per_rec.quantile(0.95)), "max": int(per_rec.max())},
        "settled_objects_per_record_mean": r(st.groupby(["seg", "t"]).size().reindex(per_rec.index, fill_value=0).mean()),
        "highest_slot_index_used": int(S.slot.max()),
        "share_of_samples_in_slots_0_4": r((S.slot <= 4).mean(), 3),
        "tracks": int(len(T)),
        "tracks_per_minute": r(len(T) / minutes, 1),
        "tracks_reaching_age_60": r((T.amax >= 60).mean(), 3),
        "track_lifetime_s": {"median": r(T.life.median()), "p90": r(T.life.quantile(0.9)), "max": r(T.life.max(), 1),
                             "share_full_file": r((T.life > 58).mean(), 3)},
        "age1_samples_at_zero_range": int(((S.age == 1) & (S.x.abs() < 0.01)).sum()),
        "share_samples_age_saturated_126": r((S.age == 126).mean(), 3),
        "ego_speed_mps": {"median": r(ego.median(), 1), "p90": r(ego.quantile(0.9), 1), "share_records_stopped": r((ego < 0.3).mean(), 3)},
        "settled_range_m": {q: r(st.x.quantile(p), 1) for q, p in (("p10", 0.1), ("p50", 0.5), ("p90", 0.9), ("max", 1.0))},
        "settled_abs_lateral_m": {q: r(st.y.abs().quantile(p), 2) for q, p in (("p50", 0.5), ("p90", 0.9))},
        "settled_motion_share": {"same_direction": r((vg > 1.5).mean(), 3), "stationary": r((vg.abs() <= 1.5).mean(), 3),
                                 "oncoming": r((vg < -1.5).mean(), 3)},
        "raw_code_ranges": {c: [int(S[c].min()), int(S[c].max())] for c in ("DREL", "YREL_LEFT", "VLONG_OVER_GROUND", "VLAT_OVER_GROUND_PROV", "ALONG_LIKE_84", "UNK_96")},
    }
    P = C[C.vcam2.notna() & (C.age >= 60)].copy()
    P["e"] = P.vrel - P.vcam2
    bands = {}
    for lo, hi in ((3, 30), (30, 60), (60, 100)):
        q = P[P.x.between(lo, hi)]
        if len(q) < 50:
            continue
        # sustained disagreement runs: |e| > 3 m/s for >= 0.5 s within one radar/camera pairing
        runs = 0
        for _, g in q.sort_values("t_r").groupby(["seg", "track", "cam_track"]):
            big, t = (g.e.abs() > 3).to_numpy(), g.t_r.to_numpy()
            k = 0
            while k < len(big):
                if big[k]:
                    j = k
                    while j + 1 < len(big) and big[j + 1] and t[j + 1] - t[j] < 0.2:
                        j += 1
                    runs += int(t[j] - t[k] >= 0.5)
                    k = j + 1
                else:
                    k += 1
        hours = q.groupby(["seg", "track", "cam_track"]).t_r.agg(lambda t: t.max() - t.min()).sum() / 3600
        bands[f"{lo}-{hi}"] = {"pairs": int(len(q)), "median_abs_diff": r(q.e.abs().median()), "p90_abs_diff": r(q.e.abs().quantile(0.9)),
                               "share_abs_diff_gt2": r((q.e.abs() > 2).mean(), 3), "share_abs_diff_gt4": r((q.e.abs() > 4).mean(), 3),
                               "disagreement_runs_ge_0.5s": runs, "paired_track_hours": r(hours, 2),
                               "runs_per_paired_track_hour": r(runs / hours, 1) if hours > 0 else None}
    out["camera_pairs"] = {"rows": int(len(C)), "settled_rows_with_camera_rate": int(len(P)),
                           "camera_vehicles": int(C.groupby(["seg", "cam_track"]).ngroups), "vrel_minus_camera_by_band": bands}
    return out


def md(stats: dict) -> str:
    d = list(stats["drives"])
    L = ["# 12. Statistics of the shipped dataset", "",
         "Generated by `tools/compute_stats.py` from `data/analysis/` (RAW_CONFIG decode, every occupied slot with age >= 1). "
         "Machine-readable copy: `data/analysis/stats.json`. Camera differences are **disagreements**, not isolated radar errors: "
         "they include reference noise, shared radar-range scale and association errors. They can overstate or understate radar error; "
         "the three-cornered hat does not establish an error bound ([05](05_validation.md)). Track lifetimes are segment-censored, "
         "not full physical-track lifetimes.", ""]

    def row(label, f):
        return f"| {label} | " + " | ".join(str(f(stats["drives"][k])) for k in d) + " |"
    L.append("| | " + " | ".join(NAMES[k] for k in d) + " |")
    L.append("|---|" + "---|" * len(d))
    rows = [
        ("segments (1 min files)", lambda s: s["segments"]),
        ("minutes decoded", lambda s: s["minutes_decoded"]),
        ("0x80 records with >= 1 object (rate /s; all records arrive at 16.7 /s)", lambda s: f"{s['records']:,} ({s['records_per_s']})"),
        ("object samples", lambda s: f"{s['object_samples']:,}"),
        ("objects per record: mean / p95 / max", lambda s: f"{s['objects_per_record']['mean']} / {s['objects_per_record']['p95']} / {s['objects_per_record']['max']}"),
        ("settled (age >= 60) objects per record, mean", lambda s: s["settled_objects_per_record_mean"]),
        ("highest slot index used (of 0-19)", lambda s: s["highest_slot_index_used"]),
        ("share of samples in slots 0-4", lambda s: s["share_of_samples_in_slots_0_4"]),
        ("tracks (per minute)", lambda s: f"{s['tracks']} ({s['tracks_per_minute']})"),
        ("tracks reaching age 60", lambda s: s["tracks_reaching_age_60"]),
        ("track lifetime s: median / p90 / max", lambda s: f"{s['track_lifetime_s']['median']} / {s['track_lifetime_s']['p90']} / {s['track_lifetime_s']['max']}"),
        ("tracks spanning a whole 1 min file", lambda s: s["track_lifetime_s"]["share_full_file"]),
        ("age-1 samples at exactly 0 m (placeholders)", lambda s: s["age1_samples_at_zero_range"]),
        ("samples at saturated age 126", lambda s: s["share_samples_age_saturated_126"]),
        ("ego speed m/s: median / p90; share stopped", lambda s: f"{s['ego_speed_mps']['median']} / {s['ego_speed_mps']['p90']}; {s['ego_speed_mps']['share_records_stopped']}"),
        ("settled dRel m: p10 / p50 / p90 / max", lambda s: " / ".join(str(v) for v in s["settled_range_m"].values())),
        ("settled \\|yRel\\| m: p50 / p90", lambda s: f"{s['settled_abs_lateral_m']['p50']} / {s['settled_abs_lateral_m']['p90']}"),
        ("settled motion: same way / stationary / oncoming", lambda s: " / ".join(str(v) for v in s["settled_motion_share"].values())),
        ("camera-paired rows (settled with box-growth rate)", lambda s: f"{s['camera_pairs']['rows']:,} ({s['camera_pairs']['settled_rows_with_camera_rate']:,})"),
        ("camera vehicles", lambda s: s["camera_pairs"]["camera_vehicles"]),
    ]
    L += [row(a, b) for a, b in rows]
    L += ["", "## Raw native vRel minus camera box growth (settled tracks)", "",
          "| drive | band | pairs | median \\|diff\\| | p90 \\|diff\\| | share > 2 m/s | share > 4 m/s | runs \\|diff\\| > 3 m/s for >= 0.5 s | per paired track-hour |",
          "|---|---|---|---|---|---|---|---|---|"]
    for k in d:
        for b, v in stats["drives"][k]["camera_pairs"]["vrel_minus_camera_by_band"].items():
            L.append(f"| {k} | {b} m | {v['pairs']:,} | {v['median_abs_diff']} | {v['p90_abs_diff']} | {v['share_abs_diff_gt2']} | "
                     f"{v['share_abs_diff_gt4']} | {v['disagreement_runs_ge_0.5s']} | {v['runs_per_paired_track_hour']} |")
    L += ["", "Disagreement runs mix radar excursions with camera failures (box jumps, occlusion, tracker swaps). "
              "`docs/img/analysis/excursion_gallery.png` shows the subset the radar's own range attributes to the radar.", "",
          "## Raw code ranges seen", "", "| field | " + " | ".join(d) + " |", "|---|" + "---|" * len(d)]
    for f in stats["drives"][d[0]]["raw_code_ranges"]:
        L.append(f"| `{f}` | " + " | ".join(f"{stats['drives'][k]['raw_code_ranges'][f][0]}-{stats['drives'][k]['raw_code_ranges'][f][1]}" for k in d) + " |")
    return "\n".join(L) + "\n"


def main() -> int:
    S, C = pd.read_parquet(DATA / "slots.parquet"), pd.read_parquet(DATA / "camera_pairs.parquet")
    stats = {"drives": {d: drive_stats(S[S.drive == d], C[C.drive == d]) for d in sorted(S.drive.unique())}}
    (DATA / "stats.json").write_text(json.dumps(stats, indent=1) + "\n")
    DOC.write_text(md(stats))
    print(DOC.read_text())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
